### ISSUE TITLE
录制结束后返回，再次进行录制的时候，不能合成视频

### ISSUE THREAD

**Issue by masterzhang** [qdrzwd/VideoRecorder#53]
录制结束后返回，再次进行录制的时候，不能合成视频，录制出来的是黑屏的，只有声音

**Comment by meunicorn** [comment]
@masterzhang 请问是否解决了这个问题？可以讨论一下吗？

**Comment by masterzhang** [comment]
@meunicorn 我已经解决了，好像是有一个变量他设置static了，找到那个属性设置成对象属性就好了
